# Generated by Django 4.1.3 on 2022-11-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_color_color_code_alter_blog_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='upload/%Y/%m'),
        ),
    ]
