# Generated by Django 4.1.3 on 2022-11-29 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_baseproduct_material_blog_gender_type_active_rating_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('size', 'product_color')},
        ),
    ]
