# Generated by Django 4.1.3 on 2022-11-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(choices=[(0, 'man'), (1, 'women')], default=0, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'base_product')},
        ),
        migrations.AlterUniqueTogether(
            name='productcolor',
            unique_together={('color', 'base_product')},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'base_product')},
        ),
    ]
