# Generated by Django 4.1.3 on 2022-11-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'init'), (1, 'waiting'), (2, 'transporting'), (3, 'received'), (4, 'cancel')], default=0),
        ),
    ]
